// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdo-iwYJ3mWmvgLXummtjPnUSe_0vuYE',
    appId: '1:323307406790:web:649227e045c7eba5629ec7',
    messagingSenderId: '323307406790',
    projectId: 'myfirstapp-35d39',
    authDomain: 'myfirstapp-35d39.firebaseapp.com',
    storageBucket: 'myfirstapp-35d39.firebasestorage.app',
    measurementId: 'G-Y8FLSW3Q3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHZRPgwWuM1eLB6-_87lFJkzf0B8pNHZs',
    appId: '1:323307406790:android:e5dc1c1d7dc72e82629ec7',
    messagingSenderId: '323307406790',
    projectId: 'myfirstapp-35d39',
    storageBucket: 'myfirstapp-35d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcHAxviiCAQ7k1LS8mbmp_e8VBEM15a34',
    appId: '1:323307406790:ios:96332efb24008cbd629ec7',
    messagingSenderId: '323307406790',
    projectId: 'myfirstapp-35d39',
    storageBucket: 'myfirstapp-35d39.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcHAxviiCAQ7k1LS8mbmp_e8VBEM15a34',
    appId: '1:323307406790:ios:96332efb24008cbd629ec7',
    messagingSenderId: '323307406790',
    projectId: 'myfirstapp-35d39',
    storageBucket: 'myfirstapp-35d39.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjdo-iwYJ3mWmvgLXummtjPnUSe_0vuYE',
    appId: '1:323307406790:web:1425f94407cdc34c629ec7',
    messagingSenderId: '323307406790',
    projectId: 'myfirstapp-35d39',
    authDomain: 'myfirstapp-35d39.firebaseapp.com',
    storageBucket: 'myfirstapp-35d39.firebasestorage.app',
    measurementId: 'G-8ZTFRE71QD',
  );
}
